// AI办公效率工具数据 - 60款精选
const toolsData = [
    // ========== 会议日程 (8款) ==========
    {
        id: 1,
        name: "飞书妙记",
        category: "meeting",
        categoryName: "会议日程",
        icon: "logos/feishu.png",
        iconType: "image",
        tagline: "会议录音转文字，自动生成纪要",
        rating: 4.8,
        price: "免费",
        url: "https://www.feishu.cn/product/minutes",
        pros: ["中文语音识别准确率极高", "免费额度非常 generous", "自动提取会议重点和待办", "与飞书文档无缝整合"],
        cons: ["需要飞书账号", "长会议处理时间较长"],
        bestFor: "经常开会的团队、需要做会议纪要的人",
        myExperience: "用了3个月，每周省2小时整理纪要。1小时会议5分钟出文字稿，准确率90%+。",
        tips: "录音时手机放桌子中间，识别效果更好"
    },
    {
        id: 2,
        name: "通义听悟",
        category: "meeting",
        categoryName: "会议日程",
        icon: "logos/tingwu.png",
        iconType: "image",
        tagline: "阿里出品，音视频智能总结",
        rating: 4.5,
        price: "免费",
        url: "https://tingwu.aliyun.com",
        pros: ["支持实时转写和文件转写", "章节速览功能很赞", "提取问答对和待办", "与钉钉整合"],
        cons: ["界面不如飞书妙记简洁", "免费额度有限"],
        bestFor: "用钉钉的团队、需要分析播客/视频的人",
        myExperience: "和飞书妙记差不多，但分析视频更强。我用来整理行业播客，15分钟节目2分钟抓重点。",
        tips: "上传视频文件时，选择'提取PPT'能自动抓屏幕内容"
    },
    {
        id: 3,
        name: "讯飞听见",
        category: "meeting",
        categoryName: "会议日程",
        icon: "logos/iflyrec.png",
        iconType: "image",
        tagline: "语音识别老字号",
        rating: 4.6,
        price: "免费+付费",
        url: "https://www.iflyrec.com",
        pros: ["语音识别准确率行业顶尖", "支持多种方言", "专业术语识别强", "有同传功能"],
        cons: ["免费额度少", "界面有点老旧"],
        bestFor: "对准确率要求极高的场景、有方言需求",
        myExperience: "准确率确实比飞书妙记高一点点，但贵。重要会议或方言场景才用。",
        tips: "专业会议前，先在设置里添加行业术语，识别更准确"
    },
    {
        id: 4,
        name: "讯飞智文",
        category: "meeting",
        categoryName: "会议日程",
        icon: "🎤",
        tagline: "讯飞出品，语音生成PPT",
        rating: 4.0,
        price: "免费",
        url: "https://zhiwen.xfyun.cn",
        pros: ["语音输入直接生成PPT", "中文语音转文字准确", "多种模板可选", "完全免费"],
        cons: ["设计感一般", "语音输入需要练习", "复杂结构支持有限"],
        bestFor: "懒得打字、习惯语音输入的人",
        myExperience: "通勤时语音说大纲，到公司PPT已经生成好了。虽然要再调整，但框架已经有了。",
        tips: "说话时按'首先、其次、最后'的结构，生成逻辑更清晰"
    },
    {
        id: 5,
        name: "钉钉闪记",
        category: "meeting",
        categoryName: "会议日程",
        icon: "⚡",
        tagline: "钉钉内置会议记录",
        rating: 4.3,
        price: "免费",
        url: "https://www.dingtalk.com",
        pros: ["与钉钉会议无缝整合", "实时转写+会后总结", "自动提取待办", "团队协作友好"],
        cons: ["需使用钉钉会议", "免费版有时长限制", "个人用户功能少"],
        bestFor: "用钉钉办公的企业团队",
        myExperience: "开钉钉会议自动记录，会后直接看文字版，不用单独再用一个工具。",
        tips: "开启'智能纪要'功能，会后自动生成结构化纪要"
    },
    {
        id: 6,
        name: "Otter.ai",
        category: "meeting",
        categoryName: "会议日程",
        icon: "🦦",
        tagline: "英文会议记录神器",
        rating: 4.5,
        price: "免费+付费",
        url: "https://otter.ai",
        pros: ["英文识别准确率极高", "实时转写+关键词提取", "与Zoom/Google Meet整合", "支持多人标记"],
        cons: ["中文支持一般", "需翻墙访问", "免费版额度少"],
        bestFor: "英文会议、跨国团队",
        myExperience: "和国外客户开会必备，实时转写让我能专注对话，不用担心漏听。",
        tips: "提前导入会议议程，AI会按议程结构整理内容"
    },
    {
        id: 7,
        name: "Fireflies.ai",
        category: "meeting",
        categoryName: "会议日程",
        icon: "🔥",
        tagline: "自动记录和分析会议",
        rating: 4.4,
        price: "免费+付费",
        url: "https://fireflies.ai",
        pros: ["自动加入会议记录", "对话分析和情绪识别", "CRM整合", "强大的搜索功能"],
        cons: ["需翻墙", "中文支持有限", "高级功能贵"],
        bestFor: "销售团队、需要分析会议质量的管理者",
        myExperience: "自动记录所有会议，搜索关键词能快速找到某次会议的讨论内容。",
        tips: "用'话题追踪'功能，看某个议题在多次会议中的讨论进展"
    },
    {
        id: 8,
        name: "腾讯会议AI",
        category: "meeting",
        categoryName: "会议日程",
        icon: "🎥",
        tagline: "腾讯会议内置AI助手",
        rating: 4.2,
        price: "部分免费",
        url: "https://meeting.tencent.com",
        pros: ["与腾讯会议深度整合", "实时转写+会后总结", "支持中英文", "国内访问稳定"],
        cons: ["高级功能需会员", "总结质量一般", "需使用腾讯会议"],
        bestFor: "用腾讯会议的用户",
        myExperience: "开会时自动记录，会后看总结回顾。虽然不如飞书妙记详细，但方便。",
        tips: "开启'会议纪要'功能，会后自动发送到邮箱"
    },

    // ========== 文档写作 (10款) ==========
    {
        id: 9,
        name: "Kimi",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/kimi.png",
        iconType: "image",
        tagline: "超长文本处理，一次读100页PDF",
        rating: 4.7,
        price: "免费",
        url: "https://kimi.moonshot.cn",
        pros: ["支持200万字上下文（行业最强）", "上传PDF直接问答", "中文理解能力优秀", "完全免费"],
        cons: ["高峰期偶尔排队", "不能联网搜索"],
        bestFor: "需要处理长文档、写报告总结的人",
        myExperience: "读100页行业报告，问3个问题就抓到重点。写周报时丢进去一周的工作记录，自动整理成结构化的汇报。",
        tips: "把多个相关文档一起上传，Kimi能跨文档关联分析"
    },
    {
        id: 10,
        name: "WPS AI",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/wps.png",
        iconType: "image",
        tagline: "国产办公套件内置AI",
        rating: 4.3,
        price: "部分免费",
        url: "https://www.wps.cn",
        pros: ["与WPS深度整合，无缝衔接", "符合国内用户习惯", "支持写文档、做PPT、分析表格", "模板丰富"],
        cons: ["高级功能需会员", "AI能力不如专业大模型"],
        bestFor: "习惯用WPS办公的人、企业用户",
        myExperience: "写通知、简报很快，但深度内容还是Kimi更强。做PPT大纲还行，设计感一般。",
        tips: "先用Kimi写内容，再用WPS排版，组合使用"
    },
    {
        id: 11,
        name: "文心一言",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/baidu.png",
        iconType: "image",
        tagline: "百度出品，国产大模型",
        rating: 4.2,
        price: "免费+付费",
        url: "https://yiyan.baidu.com",
        pros: ["国内访问稳定快速", "支持联网搜索", "多模态（文生图）", "插件生态丰富"],
        cons: ["创意能力不如GPT/Kimi", "免费版有次数限制", "偶尔有广告感"],
        bestFor: "需要稳定访问、联网搜索的人",
        myExperience: "查最新信息时用它，能搜到最新新闻。写公文、通知类内容很规范。",
        tips: "开启'联网搜索'模式，问时效性问题更准确"
    },
    {
        id: 12,
        name: "秘塔AI搜索",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/metaso.png",
        iconType: "image",
        tagline: "没有广告的AI搜索引擎",
        rating: 4.5,
        price: "免费",
        url: "https://metaso.cn",
        pros: ["搜索结果直接呈现答案", "自动总结多来源信息", "没有广告干扰", "支持追问"],
        cons: ["部分专业领域信息不够深", "实时性不如传统搜索"],
        bestFor: "需要快速获取信息、写研究报告的人",
        myExperience: "写行业分析时用它搜背景资料，直接给总结好的答案，不用翻10个网页。比百度高效多了。",
        tips: "用'总结'、'对比'、'分析'等词开头，结果更结构化"
    },
    {
        id: 13,
        name: "腾讯元宝",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/yuanbao.png",
        iconType: "image",
        tagline: "腾讯混元大模型AI助手",
        rating: 4.2,
        price: "免费",
        url: "https://yuanbao.tencent.com",
        pros: ["腾讯出品，国内访问稳定", "支持联网搜索", "微信生态整合", "完全免费"],
        cons: ["能力中规中矩", "特色不够鲜明", "新用户需排队"],
        bestFor: "需要稳定可用的通用AI助手",
        myExperience: "Kimi排队时用它应急，写个通知、查个资料够用。和微信生态结合好，分享方便。",
        tips: "开启'深度思考'模式，回答质量会提升"
    },
    {
        id: 14,
        name: "小浣熊AI",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/raccoon.png",
        iconType: "image",
        tagline: "商汤出品，办公助手",
        rating: 4.0,
        price: "免费",
        url: "https://raccoon.sensetime.com",
        pros: ["商汤大模型，中文能力强", "支持代码、写作、问答", "完全免费", "响应速度快"],
        cons: ["知名度较低", "功能中规中矩", "生态不完善"],
        bestFor: "想尝试国产大模型的用户",
        myExperience: "备用AI助手，Kimi排队时用它。写代码和写文章都能用，免费稳定。",
        tips: "用'编程助手'模式写代码，有代码补全功能"
    },
    {
        id: 15,
        name: "百度文库AI",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/wenku.png",
        iconType: "image",
        tagline: "文档生成+资料搜索",
        rating: 4.1,
        price: "部分免费",
        url: "https://wenku.baidu.com",
        pros: ["基于百度文库海量资料", "AI生成PPT、报告、简历", "资料搜索+生成一体化", "模板丰富"],
        cons: ["优质内容需会员", "生成内容有时套路化", "广告较多"],
        bestFor: "需要参考大量资料、写标准文档的人",
        myExperience: "写行业报告时用它搜资料，顺便生成PPT框架。资料全但深度一般，适合入门了解。",
        tips: "先用AI生成大纲，再针对性搜索资料填充"
    },
    {
        id: 16,
        name: "智谱清言",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/chatglm.png",
        iconType: "image",
        tagline: "清华系大模型，GLM-4",
        rating: 4.4,
        price: "免费",
        url: "https://chatglm.cn",
        pros: ["清华技术背景，学术能力强", "支持长文本", "代码能力不错", "完全免费"],
        cons: ["高峰期需排队", "创意能力一般", "界面较简单"],
        bestFor: "需要学术写作、代码辅助的用户",
        myExperience: "写技术文档和代码注释用它，逻辑清晰。学术类问题回答得比Kimi更专业。",
        tips: "用'代码模式'写代码，有语法高亮和解释"
    },
    {
        id: 17,
        name: "天工AI",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/tiangong.png",
        iconType: "image",
        tagline: "昆仑万维，全能AI助手",
        rating: 4.1,
        price: "免费",
        url: "https://www.tiangong.cn",
        pros: ["支持联网搜索", "多模态能力", "音乐生成", "完全免费"],
        cons: ["知名度不如Kimi", "写作质量中等", "功能杂而不精"],
        bestFor: "需要多功能AI助手的用户",
        myExperience: "功能很多，搜索、写作、画图都能干。但单项不如专业工具，适合不想开多个应用的人。",
        tips: "用'AI写作'功能时，指定文体和字数，结果更准确"
    },
    {
        id: 18,
        name: "海螺AI",
        category: "writing",
        categoryName: "文档写作",
        icon: "logos/hailuo.png",
        iconType: "image",
        tagline: "MiniMax出品，长文本处理",
        rating: 4.0,
        price: "免费",
        url: "https://hailuoai.com",
        pros: ["支持长文本", "语音对话", "中文理解好", "完全免费"],
        cons: ["知名度低", "功能较简单", "生态不完善"],
        bestFor: "需要语音交互、长文本处理的用户",
        myExperience: "语音输入很方便，开车时也能用。长文本能力和Kimi差不多，但不用排队。",
        tips: "用语音模式时，说话清晰慢一点，识别更准确"
    },

    // ========== PPT演示 (10款) ==========
    {
        id: 19,
        name: "美图AI PPT",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/meitu.png",
        iconType: "image",
        tagline: "一句话生成PPT",
        rating: 4.2,
        price: "免费+付费",
        url: "https://www.designkit.com/ppt/",
        pros: ["输入主题自动生成完整PPT", "模板设计感不错", "支持在线编辑", "国内访问快"],
        cons: ["免费版有水印", "生成后需要较多调整", "复杂逻辑PPT不太行"],
        bestFor: "时间紧、需要快速出PPT的人",
        myExperience: "应急神器！10分钟出一份能看的PPT。但重要汇报还是建议自己改改，别直接交。",
        tips: "提示词写详细点，比如'给老板看的季度汇报，商务风格，包含数据图表'"
    },
    {
        id: 20,
        name: "Gamma",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/gamma.png",
        iconType: "image",
        tagline: "AI生成高颜值演示文档",
        rating: 4.5,
        price: "免费+付费",
        url: "https://gamma.app",
        pros: ["设计感远超其他AI PPT工具", "支持交互式演示", "一键切换多种主题风格", "导出PDF/PPT格式"],
        cons: ["免费版有水印和数量限制", "需要翻墙访问", "中文排版偶尔有问题"],
        bestFor: "追求设计感、要做对外演示的人",
        myExperience: "做出来的PPT像设计师做的，客户看了都说专业。但中文内容有时需要微调排版。",
        tips: "先用中文写大纲，生成后再微调，比直接中文生成效果好"
    },
    {
        id: 21,
        name: "iSlide AI",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/islide.png",
        iconType: "image",
        tagline: "PPT设计神器插件",
        rating: 4.3,
        price: "部分免费",
        url: "https://www.islide.cc",
        pros: ["插件形式，兼容Office/WPS", "海量模板和素材库", "一键统一排版配色", "智能图表生成"],
        cons: ["高级素材需会员", "AI功能相对简单", "安装插件稍显麻烦"],
        bestFor: "经常做PPT的职场人、需要统一风格的企业",
        myExperience: "做PPT时直接在里面选模板、插图表，不用到处找素材。一键统一字体颜色，拯救了混乱的排版。",
        tips: "先用AI生成内容大纲，再用iSlide美化，效率最高"
    },
    {
        id: 22,
        name: "讯飞智文",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/zhiven.png",
        iconType: "image",
        tagline: "讯飞出品，语音生成PPT",
        rating: 4.0,
        price: "免费",
        url: "https://zhiwen.xfyun.cn",
        pros: ["语音输入直接生成PPT", "中文语音转文字准确", "多种模板可选", "完全免费"],
        cons: ["设计感一般", "语音输入需要练习", "复杂结构支持有限"],
        bestFor: "懒得打字、习惯语音输入的人",
        myExperience: "通勤时语音说大纲，到公司PPT已经生成好了。虽然要再调整，但框架已经有了。",
        tips: "说话时按'首先、其次、最后'的结构，生成逻辑更清晰"
    },
    {
        id: 23,
        name: "ChatPPT",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/chatppt.png",
        iconType: "image",
        tagline: "对话式生成PPT",
        rating: 4.1,
        price: "免费+付费",
        url: "https://www.chatppt.com",
        pros: ["对话式交互，像聊天一样做PPT", "理解中文指令准确", "支持在线编辑", "模板更新快"],
        cons: ["设计感中等", "免费版功能有限", "导出格式有时有问题"],
        bestFor: "喜欢对话交互、不想学复杂操作的人",
        myExperience: "像有个助手在帮你做PPT，说'加一页市场分析'、'换个蓝色主题'，马上就改好。",
        tips: "多轮对话逐步完善，比一次生成所有内容效果更好"
    },
    {
        id: 24,
        name: "ProcessOn",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/processon.png",
        iconType: "image",
        tagline: "在线作图+AI生成流程图",
        rating: 4.3,
        price: "免费+付费",
        url: "https://www.processon.com",
        pros: ["AI一键生成流程图、思维导图", "在线协作，团队实时编辑", "模板丰富，涵盖多种图表", "导出格式多样"],
        cons: ["免费版文件数有限", "AI生成复杂流程图需调整", "高级功能需会员"],
        bestFor: "需要画流程图、思维导图的职场人",
        myExperience: "画产品流程图时，描述需求AI自动生成初版，我再微调，比从零画省一半时间。",
        tips: "描述清楚流程的输入、处理、输出，AI生成更准确"
    },
    {
        id: 25,
        name: "MindShow",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/mindshow.png",
        iconType: "image",
        tagline: "导入大纲自动生成PPT",
        rating: 4.0,
        price: "免费+付费",
        url: "https://www.mindshow.fun",
        pros: ["支持Markdown导入", "一键切换多种主题", "在线演示功能", "模板设计感强"],
        cons: ["免费版功能受限", "中文排版偶有瑕疵", "导出格式有限"],
        bestFor: "习惯用Markdown写大纲的人",
        myExperience: "用Typora写好汇报大纲，直接导入生成PPT，不用重复排版。适合技术向的汇报。",
        tips: "大纲用'#'、'##'、'###'区分层级，生成结构更清晰"
    },
    {
        id: 26,
        name: "Beautiful.ai",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/beautifulai.png",
        iconType: "image",
        tagline: "智能设计，自动排版",
        rating: 4.4,
        price: "付费",
        url: "https://www.beautiful.ai",
        pros: ["AI自动调整排版", "设计感专业", "智能图表", "团队协作"],
        cons: ["需翻墙", "较贵", "中文支持一般"],
        bestFor: "追求设计感、预算充足的用户",
        myExperience: "输入内容自动排版，不用调来调去。设计感确实好，但价格劝退。",
        tips: "用Smart Slide功能，内容变化时排版自动调整"
    },
    {
        id: 27,
        name: "Tome",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/tome.png",
        iconType: "image",
        tagline: "AI叙事，讲故事的PPT",
        rating: 4.3,
        price: "免费+付费",
        url: "https://tome.app",
        pros: ["AI生成叙事型PPT", "支持图片生成", "交互式演示", "设计现代"],
        cons: ["需翻墙", "中文支持有限", "免费版功能少"],
        bestFor: "需要做故事型、创意型演示的人",
        myExperience: "做融资路演、产品发布很合适，讲故事的逻辑清晰，设计感强。",
        tips: "用'Create'功能输入主题，AI自动生成完整故事线"
    },
    {
        id: 28,
        name: "Canva可画",
        category: "ppt",
        categoryName: "PPT演示",
        icon: "logos/canva.png",
        iconType: "image",
        tagline: "在线设计+AI生成",
        rating: 4.5,
        price: "免费+付费",
        url: "https://www.canva.cn",
        pros: ["海量模板素材", "AI生成功能", "在线协作", "国内访问稳定"],
        cons: ["高级功能需会员", "AI能力不如专业工具", "功能多学习成本高"],
        bestFor: "需要一站式设计解决方案的人",
        myExperience: "不只是PPT，海报、简历、社交媒体图都能做。AI功能锦上添花，但模板才是核心。",
        tips: "用'Magic Design'功能，上传草稿AI自动美化"
    },

    // ========== 邮件沟通 (6款) ==========
    {
        id: 29,
        name: "豆包",
        category: "email",
        categoryName: "邮件沟通",
        icon: "logos/doubao.png",
        iconType: "image",
        tagline: "字节出品，中文写作助手",
        rating: 4.4,
        price: "免费",
        url: "https://www.doubao.com",
        pros: ["中文写作很地道", "支持多种语气风格", "响应速度快", "完全免费"],
        cons: ["长文本能力不如Kimi", "创意类写作一般"],
        bestFor: "需要写中文文案、邮件的人",
        myExperience: "写邮件、通知、朋友圈文案很顺手。让改语气（正式/轻松/专业）切换很丝滑。",
        tips: "写邮件时说明场景，比如'给客户的道歉邮件，语气诚恳专业'"
    },
    {
        id: 30,
        name: "DeepL Write",
        category: "email",
        categoryName: "邮件沟通",
        icon: "logos/deepl.png",
        iconType: "image",
        tagline: "AI写作助手，比Grammarly更自然",
        rating: 4.5,
        price: "部分免费",
        url: "https://www.deepl.com/write",
        pros: ["改写后的英文非常自然", "保持原意的同时优化表达", "支持多种改写风格", "界面简洁优雅"],
        cons: ["只支持英文", "高级功能需付费", "需翻墙访问"],
        bestFor: "需要写英文邮件、文档的人",
        myExperience: "比Grammarly改得更自然，不像机器翻译。写英文邮件时先写草稿，丢进去润色一遍，专业度提升明显。",
        tips: "选择'专业'风格写商务邮件，'简单'风格写日常沟通"
    },
    {
        id: 31,
        name: "火山写作",
        category: "email",
        categoryName: "邮件沟通",
        icon: "logos/writingo.png",
        iconType: "image",
        tagline: "字节旗下AI写作工具",
        rating: 4.1,
        price: "免费",
        url: "https://writingo.net",
        pros: ["专注写作场景，功能精简", "改写、续写、扩写一键完成", "支持多种文风", "完全免费"],
        cons: ["功能相对单一", "长文本处理能力一般", "知名度不高"],
        bestFor: "专注写作、不需要复杂功能的用户",
        myExperience: "写公众号文章时用它润色，改写功能很顺手，能给出多种表达方式选择。",
        tips: "选中文字后右键，有更多AI操作选项"
    },
    {
        id: 32,
        name: "Grammarly",
        category: "email",
        categoryName: "邮件沟通",
        icon: "logos/grammarly.png",
        iconType: "image",
        tagline: "英文写作纠错神器",
        rating: 4.4,
        price: "免费+付费",
        url: "https://www.grammarly.com",
        pros: ["实时纠错，插件方便", "语法、拼写、风格检查", "与邮件/文档软件整合", "免费版够用"],
        cons: ["只支持英文", "需翻墙", "高级功能贵", "有时过于严格"],
        bestFor: "需要写英文邮件、文档的人",
        myExperience: "写英文邮件必备，实时纠错避免尴尬错误。免费版够日常用。",
        tips: "设置写作目标（受众、风格、情感），建议更精准"
    },
    {
        id: 33,
        name: "ChatExcel",
        category: "data",
        categoryName: "数据处理",
        icon: "logos/chatexcel.png",
        iconType: "image",
        tagline: "对话式操作Excel",
        rating: 4.0,
        price: "免费",
        url: "https://chatexcel.com",
        pros: ["自然语言处理表格", "不用记公式", "支持数据分析、图表生成", "国产，中文理解好"],
        cons: ["复杂操作还不够智能", "大表格处理慢"],
        bestFor: "Excel小白、需要快速处理数据的人",
        myExperience: "简单筛选、求和、排序没问题。但复杂的数据透视表还是得手搓。适合应急和简单分析。",
        tips: "描述越具体越好，比如'把A列重复的行删掉，然后在B列求和'"
    },
    {
        id: 34,
        name: "Remove.bg",
        category: "data",
        categoryName: "数据处理",
        icon: "logos/removebg.png",
        iconType: "image",
        tagline: "AI自动抠图，一键去背景",
        rating: 4.6,
        price: "免费+付费",
        url: "https://www.remove.bg",
        pros: ["抠图效果极其精准", "完全自动，无需手动调整", "支持批量处理", "免费版足够个人使用"],
        cons: ["复杂背景偶尔有瑕疵", "高清图需付费", "需翻墙访问"],
        bestFor: "需要做证件照、产品图、设计素材的人",
        myExperience: "做PPT需要透明背景的产品图，上传后3秒搞定，边缘处理得比我自己抠的还干净。",
        tips: "人物照片效果最好，复杂图案可再用美图秀秀微调"
    },
    {
        id: 35,
        name: "SheetAI",
        category: "data",
        categoryName: "数据处理",
        icon: "logos/sheetai.svg",
        iconType: "image",
        tagline: "Google表格AI插件",
        rating: 4.2,
        price: "付费",
        url: "https://sheetai.app",
        pros: ["直接在Google表格里用AI", "用自然语言生成公式", "自动数据分析", "支持GPT-4"],
        cons: ["需翻墙使用", "需付费订阅", "只支持Google表格"],
        bestFor: "用Google表格、需要AI辅助的用户",
        myExperience: "在Google表格里直接问AI'计算这列的平均值并标出异常值'，公式自动生成，太方便了。",
        tips: "用=AI()函数调用，可以自定义提示词"
    },
    {
        id: 36,
        name: "Rows",
        category: "data",
        categoryName: "数据处理",
        icon: "logos/rows.png",
        iconType: "image",
        tagline: "AI驱动的电子表格",
        rating: 4.3,
        price: "免费+付费",
        url: "https://rows.com",
        pros: ["内置AI分析", "自然语言查询", "数据可视化", "团队协作"],
        cons: ["需翻墙", "学习成本", "高级功能付费"],
        bestFor: "需要数据分析+可视化的团队",
        myExperience: "比Excel更智能，问问题直接出图表。适合做数据报告和仪表盘。",
        tips: "用'AI Analyst'功能，自动发现数据趋势和异常"
    },
    {
        id: 37,
        name: "ChatCSV",
        category: "data",
        categoryName: "数据处理",
        icon: "📁",
        tagline: "上传CSV直接对话分析",
        rating: 4.0,
        price: "免费+付费",
        url: "https://chatcsv.com",
        pros: ["上传CSV直接问", "自动生成图表", "支持多文件", "无需代码"],
        cons: ["大文件需付费", "复杂分析有限", "需翻墙"],
        bestFor: "需要快速分析CSV数据的人",
        myExperience: "上传销售数据CSV，问几句就生成分析报告和图表，不用写Python。",
        tips: "问'Show me...'会生成可视化图表"
    },
    {
        id: 41,
        name: "Excel Formula Bot",
        category: "data",
        categoryName: "数据处理",
        icon: "🤖",
        tagline: "自然语言转Excel公式",
        rating: 4.1,
        price: "免费+付费",
        url: "https://excelformulabot.com",
        pros: ["描述需求自动生成公式", "解释公式含义", "支持Excel和Google Sheets", "免费版够用"],
        cons: ["复杂逻辑需多次尝试", "中文支持一般", "需翻墙"],
        bestFor: "记不住Excel公式的人",
        myExperience: "想实现某个功能但不知道公式怎么写，描述一下自动生成，还能学习公式逻辑。",
        tips: "描述时说明输入范围和期望输出，生成更准确"
    },
    {
        id: 42,
        name: "Formula Generator",
        category: "data",
        categoryName: "数据处理",
        icon: "⚡",
        tagline: "AI公式生成器",
        rating: 4.0,
        price: "免费",
        url: "https://formulagenerator.app",
        pros: ["免费使用", "支持Excel/Google Sheets", "解释公式", "示例丰富"],
        cons: ["功能较简单", "中文支持有限", "界面简陋"],
        bestFor: "偶尔需要公式帮助的用户",
        myExperience: "简单公式生成够用，复杂的需求还是得自己写。免费工具中算不错的。",
        tips: "用'Explain Formula'功能反向学习复杂公式"
    },

    // ========== 知识管理 (8款) ==========
    {
        id: 43,
        name: "Notion AI",
        category: "notes",
        categoryName: "知识管理",
        icon: "logos/notion.png",
        iconType: "image",
        tagline: "All-in-one知识库内置AI",
        rating: 4.6,
        price: "付费",
        url: "https://www.notion.so",
        pros: ["与Notion深度整合，笔记直接AI处理", "支持总结、续写、翻译、头脑风暴", "数据库AI查询", "团队协作神器"],
        cons: ["AI功能需付费（$10/月）", "国内访问有时不稳定", "学习成本较高"],
        bestFor: "用Notion做知识管理的人、团队协作",
        myExperience: "笔记写了一半卡住，按空格AI自动续写，灵感马上就来了。数据库太多时，直接问AI找内容。",
        tips: "选中文字后按空格唤醒AI，比全局AI更精准"
    },
    {
        id: 44,
        name: "印象笔记AI",
        category: "notes",
        categoryName: "知识管理",
        icon: "🐘",
        tagline: "老牌笔记软件内置AI",
        rating: 4.0,
        price: "部分免费",
        url: "https://www.yinxiang.com",
        pros: ["与印象笔记深度整合", "剪藏网页后AI总结", "支持中文", "国内访问稳定"],
        cons: ["AI功能较基础", "高级功能需付费", "界面略显陈旧"],
        bestFor: "印象笔记老用户、需要剪藏+总结的人",
        myExperience: "剪藏的文章一键总结要点，省了很多阅读时间。但AI能力不如Kimi，复杂分析还是得导出。",
        tips: "剪藏长文后先用AI总结，感兴趣再精读全文"
    },
    {
        id: 45,
        name: "FlowUs AI",
        category: "notes",
        categoryName: "知识管理",
        icon: "🌊",
        tagline: "国产Notion替代品",
        rating: 4.2,
        price: "部分免费",
        url: "https://flowus.cn",
        pros: ["国产，访问稳定", "类似Notion的块编辑器", "AI写作、总结功能", "模板丰富"],
        cons: ["功能比Notion少", "生态不如Notion成熟", "AI能力一般"],
        bestFor: "想要Notion体验但嫌访问慢的人",
        myExperience: "Notion的平替，基本功能都有。AI写笔记大纲够用，但深度分析还是Kimi。",
        tips: "从Notion导入数据很方便，可以无缝迁移"
    },
    {
        id: 46,
        name: "钉钉文档AI",
        category: "notes",
        categoryName: "知识管理",
        icon: "📎",
        tagline: "钉钉内置AI文档助手",
        rating: 4.0,
        price: "部分免费",
        url: "https://docs.dingtalk.com",
        pros: ["与钉钉深度整合", "支持AI写作、总结、续写", "团队协作无缝", "企业用户友好"],
        cons: ["个人用户功能有限", "AI能力不如专业工具", "需钉钉生态"],
        bestFor: "用钉钉办公的企业团队",
        myExperience: "公司用钉钉，写周报、会议纪要直接在里面完成，不用切换应用。AI写个初稿我再改。",
        tips: "用'/'唤醒AI菜单，快速调用各种功能"
    },
    {
        id: 47,
        name: "语雀AI",
        category: "notes",
        categoryName: "知识管理",
        icon: "🐦",
        tagline: "阿里出品，知识库+AI",
        rating: 4.3,
        price: "部分免费",
        url: "https://www.yuque.com",
        pros: ["国内访问稳定", "AI写作、续写、优化", "团队协作", "适合技术文档"],
        cons: ["高级功能需会员", "AI能力中等", "个人免费版有限制"],
        bestFor: "技术人员、需要写文档的团队",
        myExperience: "写技术文档很顺手，AI续写和优化功能实用。代码块支持好，适合程序员。",
        tips: "用'AI续写'时先写个大纲，生成内容更连贯"
    },
    {
        id: 48,
        name: "Obsidian",
        category: "notes",
        categoryName: "知识管理",
        icon: "🗃️",
        tagline: "本地优先的知识库+AI插件",
        rating: 4.5,
        price: "免费+付费",
        url: "https://obsidian.md",
        pros: ["本地存储，数据安全", "丰富的AI插件生态", "双向链接知识网络", "高度可定制"],
        cons: ["需自己配置AI插件", "学习成本高", "同步需额外设置"],
        bestFor: "重视数据隐私、喜欢折腾的高级用户",
        myExperience: "搭配Copilot插件实现AI功能，本地运行不用担心隐私。知识图谱功能强大。",
        tips: "安装'Copilot'插件连接OpenAI API，实现本地AI助手"
    },
    {
        id: 49,
        name: "Logseq",
        category: "notes",
        categoryName: "知识管理",
        icon: "🌳",
        tagline: "开源大纲笔记+AI",
        rating: 4.2,
        price: "免费",
        url: "https://logseq.com",
        pros: ["开源免费", "大纲式笔记", "AI插件支持", "本地优先"],
        cons: ["需配置AI插件", "界面不如Notion美观", "移动端体验一般"],
        bestFor: "喜欢大纲笔记、重视隐私的用户",
        myExperience: "大纲式笔记适合整理思路，配合AI插件可以总结和扩展内容。开源免费很良心。",
        tips: "用'Logseq Copilot'插件接入AI功能"
    },
    {
        id: 50,
        name: "Readwise Reader",
        category: "notes",
        categoryName: "知识管理",
        icon: "📖",
        tagline: "阅读管理+AI总结",
        rating: 4.4,
        price: "付费",
        url: "https://readwise.io/read",
        pros: ["稍后读+AI总结", "支持多种格式", "高亮和笔记管理", "与Readwise同步"],
        cons: ["需翻墙", "较贵", "中文支持一般"],
        bestFor: "重度阅读者、需要管理阅读资料的人",
        myExperience: "文章先存进来，AI总结要点，再决定要不要精读。阅读效率提升明显。",
        tips: "开启'Ghostreader'功能，对任意内容提问"
    },

    // ========== 产品设计 (6款) ==========
    {
        id: 51,
        name: "墨刀AI",
        category: "product",
        categoryName: "产品设计",
        icon: "✏️",
        tagline: "产品设计+AI生成原型",
        rating: 4.2,
        price: "免费+付费",
        url: "https://modao.cc",
        pros: ["AI生成产品原型", "文字描述转界面", "在线协作，团队评审", "适合产品经理"],
        cons: ["AI生成复杂页面需调整", "高级功能需付费", "学习成本略高"],
        bestFor: "产品经理、需要快速出原型的设计师",
        myExperience: "描述需求AI生成低保真原型，和客户沟通前先确认方向，减少返工。",
        tips: "描述越详细越好，包括页面元素、交互逻辑"
    },
    {
        id: 52,
        name: "MasterGo AI",
        category: "product",
        categoryName: "产品设计",
        icon: "🎨",
        tagline: "国产设计工具+AI",
        rating: 4.1,
        price: "免费+付费",
        url: "https://mastergo.com",
        pros: ["国产Figma替代品", "AI生成设计", "团队协作", "国内访问快"],
        cons: ["AI功能较新", "生态不如Figma", "高级功能付费"],
        bestFor: "需要国产设计工具的团队",
        myExperience: "Figma的国产替代，基本功能都有。AI生成设计还在完善，但日常协作够用。",
        tips: "用'AI生成'功能快速出设计初稿，再人工精调"
    },
    {
        id: 53,
        name: "即时设计",
        category: "product",
        categoryName: "产品设计",
        icon: "⚡",
        tagline: "国产在线设计工具",
        rating: 4.0,
        price: "免费",
        url: "https://js.design",
        pros: ["完全免费", "国产访问稳定", "AI生成设计", "Figma文件导入"],
        cons: ["AI能力一般", "功能不如Figma全", "大文件卡顿"],
        bestFor: "预算有限、需要免费设计工具的用户",
        myExperience: "免费版功能够用，AI生成设计素材省时间。适合个人和小团队。",
        tips: "用'AI绘画'功能生成图标和插图"
    },
    {
        id: 54,
        name: "Figma AI",
        category: "product",
        categoryName: "产品设计",
        icon: "🖌️",
        tagline: "设计工具标杆+AI",
        rating: 4.6,
        price: "免费+付费",
        url: "https://www.figma.com",
        pros: ["设计工具行业标准", "AI生成设计、自动命名", "强大的协作功能", "丰富的插件生态"],
        cons: ["需翻墙", "国内访问慢", "高级功能付费"],
        bestFor: "专业设计师、设计团队",
        myExperience: "设计团队协作首选，AI功能锦上添花。自动命名图层、生成设计建议很实用。",
        tips: "用'Make Design'功能根据文字描述生成界面"
    },
    {
        id: 55,
        name: "Uizard",
        category: "product",
        categoryName: "产品设计",
        icon: "🧙",
        tagline: "AI生成UI设计",
        rating: 4.0,
        price: "免费+付费",
        url: "https://uizard.io",
        pros: ["草图转设计", "AI生成界面", "无需设计基础", "快速原型"],
        cons: ["设计感一般", "复杂项目有限", "需翻墙"],
        bestFor: "非设计师、需要快速出原型的创业者",
        myExperience: "手绘草图拍照上传，AI转成可点击原型。适合快速验证想法。",
        tips: "手绘时线条清晰，AI识别更准确"
    },
    {
        id: 56,
        name: "Galileo AI",
        category: "product",
        categoryName: "产品设计",
        icon: "🔭",
        tagline: "文字生成UI设计",
        rating: 4.3,
        price: "付费",
        url: "https://www.usegalileo.ai",
        pros: ["文字描述直接出设计", "设计感强", "可导出Figma", "支持编辑"],
        cons: ["需翻墙", "较贵", "中文支持一般"],
        bestFor: "需要快速出高保真设计的团队",
        myExperience: "描述产品需求，直接出高保真设计图，比从零设计快10倍。",
        tips: "描述时包含风格、配色、目标用户，结果更精准"
    },

    // ========== 视频剪辑 (6款) ==========
    {
        id: 57,
        name: "剪映AI",
        category: "video",
        categoryName: "视频剪辑",
        icon: "🎬",
        tagline: "视频剪辑+AI一键成片",
        rating: 4.5,
        price: "免费",
        url: "https://www.capcut.cn",
        pros: ["AI一键生成视频", "图文转视频", "自动配音、字幕", "完全免费"],
        cons: ["AI生成视频模板感强", "高级剪辑功能有限", "导出有水印（可关）"],
        bestFor: "需要做短视频、视频汇报的人",
        myExperience: "把PPT导出图片，导入剪映AI一键生成视频汇报，自动配音加字幕，10分钟搞定。",
        tips: "用'图文成片'功能，导入图片和文案自动生成视频"
    },
    {
        id: 58,
        name: "腾讯智影",
        category: "video",
        categoryName: "视频剪辑",
        icon: "🎥",
        tagline: "腾讯出品，AI视频创作",
        rating: 4.2,
        price: "免费+付费",
        url: "https://zenvideo.qq.com",
        pros: ["AI数字人", "文本生成视频", "智能剪辑", "国内访问稳定"],
        cons: ["免费版功能有限", "数字人效果一般", "高级功能贵"],
        bestFor: "需要数字人、快速出视频的用户",
        myExperience: "用数字人做培训视频，不用真人出镜。文本转视频功能适合新闻类内容。",
        tips: "数字人视频时，文案要口语化，更像真人"
    },
    {
        id: 59,
        name: "一帧秒创",
        category: "video",
        categoryName: "视频剪辑",
        icon: "⏱️",
        tagline: "图文转视频神器",
        rating: 4.1,
        price: "免费+付费",
        url: "https://aigc.yizhentv.com",
        pros: ["文章一键转视频", "自动匹配素材", "AI配音", "国内可用"],
        cons: ["素材库有限", "视频风格单一", "免费版有水印"],
        bestFor: "自媒体、需要批量出视频的人",
        myExperience: "公众号文章直接转视频，自动配图配音乐，适合快速分发到视频平台。",
        tips: "文章分好段落，转视频时逻辑更清晰"
    },
    {
        id: 60,
        name: "度加剪辑",
        category: "video",
        categoryName: "视频剪辑",
        icon: "✂️",
        tagline: "百度出品，AI剪辑",
        rating: 4.0,
        price: "免费",
        url: "https://ducut.baidu.com",
        pros: ["AI自动剪辑", "热点推荐", "智能字幕", "完全免费"],
        cons: ["功能较基础", "素材库一般", "专业剪辑不够"],
        bestFor: "短视频创作者、剪辑新手",
        myExperience: "自动识别口播停顿并剪掉，加字幕也很方便。适合口播类短视频。",
        tips: "用'AI成片'功能，导入素材自动剪辑"
    }
];

// 分类配置
const categories = {
    all: { name: "全部", icon: "🔥" },
    writing: { name: "文档写作", icon: "✍️" },
    ppt: { name: "PPT演示", icon: "📊" },
    email: { name: "邮件沟通", icon: "📧" },
    data: { name: "数据处理", icon: "📈" },
    meeting: { name: "会议日程", icon: "🗓️" },
    notes: { name: "知识管理", icon: "📝" },
    product: { name: "产品设计", icon: "🎨" },
    video: { name: "视频剪辑", icon: "🎬" },
    design: { name: "设计创意", icon: "✨" }
};

// 导出数据（如果是模块环境）
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { toolsData, categories };
}
